### ISSUE TITLE
The main artifact is not embeded

### ISSUE THREAD

**Issue by algomaster99** [chains-project/classport#7]
We don't have access to the JAR file of the artifact in the maven plugin so we don't embed it for now.

**Comment by danielwis** [comment]
1. Force Maven to execute the `compile` phase at plugin start
2. Find a way to access the compiled class files using the Maven API (`project.getIncludes()` maybe?)
3. Embed a Classport annotation in each of these class files
4. Package using `mvn package -Dmaven.repo.local=[...]`

**Comment by danielwis** [comment]
Solved in 02211be.
